from Environments.TwoRoomsEnvironment.envs.tworoomsenvironment import TwoRoomsEnvironment
from Environments.TwoRoomsEnvironment.envs.tworoomsenvironmentv2 import TwoRoomsEnvironmentV2

from Environments.TwoRoomsEnvironment.envs.tworoomsenvironmentonleft import TwoRoomsEnvironmentOnLeft
from Environments.TwoRoomsEnvironment.envs.tworoomsenvironmentonright import TwoRoomsEnvironmentOnRight

from Environments.TwoRoomsEnvironment.envs.tworoomsenvironment1x import TwoRoomsEnvironment1X
from Environments.TwoRoomsEnvironment.envs.tworoomsenvironment2x import TwoRoomsEnvironment2X
from Environments.TwoRoomsEnvironment.envs.tworoomsenvironment3x import TwoRoomsEnvironment3X
from Environments.TwoRoomsEnvironment.envs.tworoomsenvironment4x import TwoRoomsEnvironment4X
from Environments.TwoRoomsEnvironment.envs.tworoomsenvironment5x import TwoRoomsEnvironment5X

from Environments.TwoRoomsEnvironment.envs.tworoomsenvironmentv2visualfull import TwoRoomsEnvironmentV2VisualFull